package com.atelbay.money_manager.core.ui.theme

import androidx.compose.runtime.staticCompositionLocalOf
import java.util.Locale

data class AppStrings(
    val locale: Locale,
    // ── Common ──
    val ok: String,
    val cancel: String,
    val save: String,
    val saving: String,
    val back: String,
    val delete: String,
    val done: String,
    val tryAgain: String,
    val search: String,
    val clearSearch: String,
    val all: String,
    val other: String,

    // ── Bottom nav ──
    val navTransactions: String,
    val navAccounts: String,
    val navStatistics: String,
    val navSettings: String,

    // ── Transaction types ──
    val expense: String,
    val income: String,

    // ── Transaction List ──
    val appName: String,
    val importStatement: String,
    val filterAll: String,
    val filterExpenses: String,
    val filterIncome: String,
    val periodToday: String,
    val periodYesterday: String,
    val periodWeek: String,
    val periodMonth: String,
    val periodYear: String,
    val nothingFound: String,
    val tryChangingQuery: String,
    val noTransactions: String,
    val addFirstTransaction: String,
    val originalAmount: String,
    val periodDay: String,
    val searchTransactions: String,
    val savedPercent: (percent: Int) -> String,
    val incomeCardLabel: String,
    val expenseCardLabel: String,
    val balanceCardLabel: String,

    // ── Transaction Edit ──
    val editTransaction: String,
    val newTransaction: String,
    val amount: String,
    val category: String,
    val date: String,
    val note: String,
    val noteHint: String,
    val chooseCategory: String,

    // ── Categories ──
    val categoriesTitle: String,
    val noCategories: String,

    // ── Category Edit ──
    val editCategory: String,
    val newCategory: String,
    val name: String,
    val categoryNameHint: String,
    val icon: String,
    val color: String,

    // ── Accounts ──
    val accountsTitle: String,
    val totalBalance: String,
    val allAccounts: String,
    val noAccounts: String,
    val active: String,
    val selectAccount: String,
    val noAccountsWarning: String,

    // ── Account Edit ──
    val editAccount: String,
    val newAccount: String,
    val accountNameHint: String,
    val currency: String,

    // ── Statistics ──
    val statisticsTitle: String,
    val expensesByDays: String,
    val byCategory: String,
    val noDataForPeriod: String,
    val expensesUpper: String,
    val incomeUpper: String,
    val expensesLabel: String,
    val incomeLabel: String,
    val totalExpenses: String,
    val totalIncome: String,
    val incomeByDays: String,
    val statisticsChartByDay: (subject: String) -> String,
    val statisticsChartByMonth: (subject: String) -> String,
    val statisticsDateRangeSingleMonth: (month: String, startDay: Int, endDay: Int, year: Int) -> String,
    val statisticsDateRangeCrossMonth: (start: String, end: String, year: Int) -> String,
    val statisticsDateRangeCrossYear: (start: String, end: String) -> String,
    val mixedCurrencyUnavailable: String,
    val retryButton: String,

    // ── Validation Errors ──
    val errorEnterAccountName: String,
    val errorEnterCategoryName: String,
    val errorEnterValidAmount: String,
    val errorSelectCategory: String,
    val errorSelectAccount: String,
    val errorEndDateBeforeStart: String,
    val errorEnterValidLimit: String,
    val errorReadingPdf: String,
    val errorUnknown: String,
    val errorNoTransactionsFound: String,
    val errorSelectAccountForImport: String,
    val errorImport: String,
    val errorNoInternet: String,
    val errorSignInFailed: String,
    val errorLoadCategoryTransactions: String,
    val errorUpdateRate: String,

    // ── Import ──
    val importTitle: String,
    val chooseImportMethod: String,
    val selectPdf: String,
    val takePhoto: String,
    val analyzingStatement: String,
    val importingTransactions: String,
    val importedCount: (count: Int) -> String,
    val importFound: (Int) -> String,
    val importDuplicates: (Int) -> String,
    val importReadyCount: (Int, Int) -> String,
    val importNoCategory: (Int) -> String,
    val importButton: (Int) -> String,
    val importNeedsReview: (Int) -> String,
    val importRecognized: (Int) -> String,
    val importAccountLabel: String,
    val importSelectAccount: String,

    // ── Onboarding ──
    val start: String,
    val next: String,
    val skip: String,
    val onboardingSetupTitle: String,
    val onboardingSignInRestore: String,
    val onboardingCreateNewAccount: String,
    val onboardingSkipForNow: String,
    val onboardingSyncing: String,
    val onboardingPage1Title: String,
    val onboardingPage1Desc: String,
    val onboardingPage2Title: String,
    val onboardingPage2Desc: String,
    val onboardingPage3Title: String,
    val onboardingPage3Desc: String,

    // ── Create Account (onboarding step) ──
    val createFirstAccount: String,
    val createFirstAccountSubtitle: String,
    val accountMain: String,
    val initialBalance: String,
    val creating: String,
    val createAccount: String,

    // ── Sign In ──
    val accountSectionTitle: String,
    val signInSubtitle: String,
    val signInWithGoogle: String,
    val userAvatar: String,
    val signOut: String,

    // ── Currency Picker ──
    val currencyPair: String,
    val currentPair: String,
    val baseCurrency: String,
    val targetCurrency: String,
    val searchCurrency: String,

    // ── Period / Date Filtering ──
    val currentMonth: String,
    val thirtyDays: String,
    val selectMonth: String,
    val selectRange: String,
    val customRange: String,

    // ── Recurring Transactions ──
    val recurringTransactions: String,
    val noRecurringTransactions: String,
    val daily: String,
    val weekly: String,
    val monthly: String,
    val yearly: String,
    val startDate: String,
    val endDate: String,
    val nextDate: String,
    val lastGeneratedDateLabel: String,
    val frequency: String,
    val dayOfMonth: String,
    val dayOfWeek: String,
    val dayOfWeekShort: List<String>,
    val paused: String,
    val newRecurring: String,
    val editRecurring: String,

    // ── Budgets ──
    val budgets: String,
    val budget: String,
    val limit: String,
    val spent: String,
    val remaining: String,
    val overBudget: String,
    val newBudget: String,
    val noBudgets: String,
    val monthlyLimit: String,

    // ── Export ──
    val exportCsv: String,
    val exportComplete: String,
    val exportError: String,
    val exporting: String,

    // ── Settings ──
    val settingsTitle: String,
    val sectionAccount: String,
    val sectionGeneral: String,
    val sectionAppearance: String,
    val sectionAbout: String,
    val categoriesManagement: String,
    val categoriesSubtitle: String,
    val rateLabel: (base: String, target: String) -> String,
    val rateNotLoaded: String,
    val rateAsOf: (date: String) -> String,
    val loadRate: String,
    val updatingRate: String,
    val loadRateSubtitle: String,
    val themeLabel: String,
    val themeSystem: String,
    val themeLight: String,
    val themeDark: String,
    val languageLabel: String,
    val versionLabel: String,
    val developerLabel: String,
    val syncData: String,
    val syncing: String,
    val synced: String,
    val syncError: String,
    val syncRetryHint: String,
    val updatedAt: (time: String) -> String,
    val rateError: String,
)

val RussianStrings = AppStrings(
    locale = Locale("ru"),
    ok = "OK",
    cancel = "Отмена",
    save = "Сохранить",
    saving = "Сохранение...",
    back = "Назад",
    delete = "Удалить",
    done = "Готово",
    tryAgain = "Попробовать снова",
    search = "Поиск",
    clearSearch = "Очистить",
    all = "Все",
    other = "Другое",
    navTransactions = "Главная",
    navAccounts = "Счета",
    navStatistics = "Статистика",
    navSettings = "Настройки",
    expense = "Расход",
    income = "Доход",
    appName = "Money Manager",
    importStatement = "Импорт выписки",
    filterAll = "Все",
    filterExpenses = "Расходы",
    filterIncome = "Доходы",
    periodToday = "Сегодня",
    periodYesterday = "Вчера",
    periodWeek = "Неделя",
    periodMonth = "Месяц",
    periodYear = "Год",
    nothingFound = "Ничего не найдено",
    tryChangingQuery = "Попробуйте изменить запрос",
    noTransactions = "Нет транзакций",
    addFirstTransaction = "Добавьте первую транзакцию",
    originalAmount = "Исх.",
    periodDay = "День",
    searchTransactions = "Поиск транзакций...",
    savedPercent = { percent -> "Сохранено $percent% дохода" },
    incomeCardLabel = "ДОХОД",
    expenseCardLabel = "РАСХОД",
    balanceCardLabel = "БАЛАНС",
    editTransaction = "Редактирование",
    newTransaction = "Новая транзакция",
    amount = "Сумма",
    category = "Категория",
    date = "Дата",
    note = "Заметка",
    noteHint = "Описание транзакции",
    chooseCategory = "Выберите категорию",
    categoriesTitle = "Категории",
    noCategories = "Нет категорий",
    editCategory = "Редактирование",
    newCategory = "Новая категория",
    name = "Название",
    categoryNameHint = "Название категории",
    icon = "Иконка",
    color = "Цвет",
    accountsTitle = "Счета",
    totalBalance = "Общий баланс",
    allAccounts = "Все счета",
    noAccounts = "Нет счетов",
    active = "Активный",
    selectAccount = "Выбрать",
    noAccountsWarning = "Сначала создайте счёт",
    editAccount = "Редактирование",
    newAccount = "Новый счёт",
    accountNameHint = "Название счёта",
    currency = "Валюта",
    statisticsTitle = "Статистика",
    expensesByDays = "РАСХОДЫ ПО ДНЯМ",
    byCategory = "По категориям",
    noDataForPeriod = "Нет данных за выбранный период",
    expensesUpper = "РАСХОДЫ",
    incomeUpper = "ДОХОДЫ",
    expensesLabel = "Расходы",
    incomeLabel = "Доходы",
    totalExpenses = "Итого расходы",
    totalIncome = "Итого доходы",
    incomeByDays = "ДОХОДЫ ПО ДНЯМ",
    statisticsChartByDay = { subject -> "$subject по дням" },
    statisticsChartByMonth = { subject -> "$subject по месяцам" },
    statisticsDateRangeSingleMonth = { month, startDay, endDay, year -> "$month $startDay-$endDay, $year" },
    statisticsDateRangeCrossMonth = { start, end, year -> "$start - $end, $year" },
    statisticsDateRangeCrossYear = { start, end -> "$start - $end" },
    mixedCurrencyUnavailable = "Недостаточно курсов для конвертации",
    retryButton = "Повторить",
    errorEnterAccountName = "Введите название счёта",
    errorEnterCategoryName = "Введите название категории",
    errorEnterValidAmount = "Введите корректную сумму",
    errorSelectCategory = "Выберите категорию",
    errorSelectAccount = "Выберите счёт",
    errorEndDateBeforeStart = "Дата окончания должна быть позже даты начала",
    errorEnterValidLimit = "Введите корректный лимит",
    errorReadingPdf = "Ошибка чтения PDF",
    errorUnknown = "Неизвестная ошибка",
    errorNoTransactionsFound = "Не удалось найти транзакции в документе",
    errorSelectAccountForImport = "Выберите счёт для импорта",
    errorImport = "Ошибка импорта",
    errorNoInternet = "Нет подключения к интернету",
    errorSignInFailed = "Не удалось войти. Попробуйте снова",
    errorLoadCategoryTransactions = "Не удалось загрузить транзакции",
    errorUpdateRate = "Не удалось обновить курс",
    importTitle = "Импорт выписки",
    chooseImportMethod = "Выберите способ импорта",
    selectPdf = "Выбрать PDF",
    takePhoto = "Сделать фото",
    analyzingStatement = "Анализ выписки...",
    importingTransactions = "Импорт транзакций...",
    importedCount = { count -> "Импортировано: $count" },
    importFound = { "Найдено: $it" },
    importDuplicates = { "Дубликаты: $it" },
    importReadyCount = { ready, total -> "К импорту: $ready из $total" },
    importNoCategory = { "Без категории: $it" },
    importButton = { "Импорт ($it)" },
    importNeedsReview = { "Требуют проверки ($it)" },
    importRecognized = { "Распознаны ($it)" },
    importAccountLabel = "Счёт для импорта",
    importSelectAccount = "Выберите счёт",
    start = "Начать",
    next = "Далее",
    skip = "Пропустить",
    onboardingSetupTitle = "Как вы хотите начать?",
    onboardingSignInRestore = "Войти и восстановить данные",
    onboardingCreateNewAccount = "Создать новый счёт",
    onboardingSkipForNow = "Пропустить",
    onboardingSyncing = "Восстановление данных...",
    onboardingPage1Title = "Добро пожаловать!",
    onboardingPage1Desc = "Money Manager поможет вам контролировать расходы и доходы",
    onboardingPage2Title = "Отслеживайте финансы",
    onboardingPage2Desc = "Добавляйте транзакции, распределяйте по категориям и следите за балансом",
    onboardingPage3Title = "Анализируйте траты",
    onboardingPage3Desc = "Графики и статистика помогут понять, куда уходят деньги",
    createFirstAccount = "Создайте первый счёт",
    createFirstAccountSubtitle = "Укажите название, валюту и начальный баланс",
    accountMain = "Основной",
    initialBalance = "Начальный баланс",
    creating = "Создание...",
    createAccount = "Создать счёт",
    accountSectionTitle = "Аккаунт",
    signInSubtitle = "Войдите, чтобы синхронизировать данные",
    signInWithGoogle = "Войти через Google",
    userAvatar = "Аватар пользователя",
    signOut = "Выйти",
    currencyPair = "Валютная пара",
    currentPair = "Текущая пара",
    baseCurrency = "Базовая",
    targetCurrency = "Целевая",
    searchCurrency = "Поиск валюты",
    currentMonth = "Тек. месяц",
    thirtyDays = "30 дней",
    selectMonth = "Выбрать месяц",
    selectRange = "Выбрать период",
    customRange = "Период",
    recurringTransactions = "Регулярные платежи",
    noRecurringTransactions = "Нет повторяющихся транзакций",
    daily = "Каждый день",
    weekly = "Каждую неделю",
    monthly = "Каждый месяц",
    yearly = "Каждый год",
    startDate = "Дата начала",
    endDate = "Дата окончания",
    nextDate = "Следующая дата",
    lastGeneratedDateLabel = "Последнее списание",
    frequency = "Периодичность",
    dayOfMonth = "День месяца",
    dayOfWeek = "День недели",
    dayOfWeekShort = listOf("Пн", "Вт", "Ср", "Чт", "Пт", "Сб", "Вс"),
    paused = "Приостановлен",
    newRecurring = "Новый платёж",
    editRecurring = "Редактирование",
    budgets = "Бюджеты",
    budget = "Бюджет",
    limit = "Лимит",
    spent = "Потрачено",
    remaining = "Остаток",
    overBudget = "Превышен бюджет",
    newBudget = "Новый бюджет",
    noBudgets = "Нет бюджетов",
    monthlyLimit = "Лимит на месяц",
    exportCsv = "Экспорт в CSV",
    exportComplete = "Экспорт завершён",
    exportError = "Ошибка экспорта",
    exporting = "Экспортируется...",
    settingsTitle = "Настройки",
    sectionAccount = "Аккаунт",
    sectionGeneral = "Общее",
    sectionAppearance = "Оформление",
    sectionAbout = "О приложении",
    categoriesManagement = "Категории",
    categoriesSubtitle = "Управление категориями",
    rateLabel = { base, target -> "Курс $base/$target" },
    rateNotLoaded = "Курс ещё не загружен",
    rateAsOf = { date -> "Курс на $date" },
    loadRate = "Загрузить курс НБК",
    updatingRate = "Выполняется обновление",
    loadRateSubtitle = "Загрузить актуальный курс НБК",
    themeLabel = "Тема",
    themeSystem = "Система",
    themeLight = "Светлая",
    themeDark = "Тёмная",
    languageLabel = "Язык",
    versionLabel = "Версия",
    developerLabel = "Разработчик",
    syncData = "Синхронизация данных",
    syncing = "Синхронизация...",
    synced = "Синхронизировано",
    syncError = "Ошибка синхронизации",
    syncRetryHint = "Нажмите для повтора",
    updatedAt = { time -> "Обновлено $time" },
    rateError = "Не удалось обновить курс",
)

val EnglishStrings = AppStrings(
    locale = Locale.ENGLISH,
    ok = "OK",
    cancel = "Cancel",
    save = "Save",
    saving = "Saving...",
    back = "Back",
    delete = "Delete",
    done = "Done",
    tryAgain = "Try Again",
    search = "Search",
    clearSearch = "Clear",
    all = "All",
    other = "Other",
    navTransactions = "Home",
    navAccounts = "Accounts",
    navStatistics = "Statistics",
    navSettings = "Settings",
    expense = "Expense",
    income = "Income",
    appName = "Money Manager",
    importStatement = "Import Statement",
    filterAll = "All",
    filterExpenses = "Expenses",
    filterIncome = "Income",
    periodToday = "Today",
    periodYesterday = "Yesterday",
    periodWeek = "Week",
    periodMonth = "Month",
    periodYear = "Year",
    nothingFound = "Nothing found",
    tryChangingQuery = "Try changing your search query",
    noTransactions = "No transactions",
    addFirstTransaction = "Add your first transaction",
    originalAmount = "Orig.",
    periodDay = "Day",
    searchTransactions = "Search transactions...",
    savedPercent = { percent -> "Saved $percent% of income" },
    incomeCardLabel = "INCOME",
    expenseCardLabel = "EXPENSE",
    balanceCardLabel = "BALANCE",
    editTransaction = "Edit",
    newTransaction = "New Transaction",
    amount = "Amount",
    category = "Category",
    date = "Date",
    note = "Note",
    noteHint = "Transaction description",
    chooseCategory = "Choose category",
    categoriesTitle = "Categories",
    noCategories = "No categories",
    editCategory = "Edit",
    newCategory = "New Category",
    name = "Name",
    categoryNameHint = "Category name",
    icon = "Icon",
    color = "Color",
    accountsTitle = "Accounts",
    totalBalance = "Total Balance",
    allAccounts = "All Accounts",
    noAccounts = "No accounts",
    active = "Active",
    selectAccount = "Select",
    noAccountsWarning = "Create an account first",
    editAccount = "Edit",
    newAccount = "New Account",
    accountNameHint = "Account name",
    currency = "Currency",
    statisticsTitle = "Statistics",
    expensesByDays = "EXPENSES BY DAYS",
    byCategory = "By Category",
    noDataForPeriod = "No data for selected period",
    expensesUpper = "EXPENSES",
    incomeUpper = "INCOME",
    expensesLabel = "Expenses",
    incomeLabel = "Income",
    totalExpenses = "Total expenses",
    totalIncome = "Total income",
    incomeByDays = "INCOME BY DAYS",
    statisticsChartByDay = { subject -> "$subject by day" },
    statisticsChartByMonth = { subject -> "$subject by month" },
    statisticsDateRangeSingleMonth = { month, startDay, endDay, year -> "$month $startDay-$endDay, $year" },
    statisticsDateRangeCrossMonth = { start, end, year -> "$start - $end, $year" },
    statisticsDateRangeCrossYear = { start, end -> "$start - $end" },
    mixedCurrencyUnavailable = "Not enough exchange rates to convert totals",
    retryButton = "Retry",
    errorEnterAccountName = "Enter account name",
    errorEnterCategoryName = "Enter category name",
    errorEnterValidAmount = "Enter a valid amount",
    errorSelectCategory = "Select a category",
    errorSelectAccount = "Select an account",
    errorEndDateBeforeStart = "End date must be after start date",
    errorEnterValidLimit = "Enter a valid limit",
    errorReadingPdf = "Error reading PDF",
    errorUnknown = "Unknown error",
    errorNoTransactionsFound = "No transactions found in document",
    errorSelectAccountForImport = "Select an account for import",
    errorImport = "Import error",
    errorNoInternet = "No internet connection",
    errorSignInFailed = "Sign-in failed. Please try again",
    errorLoadCategoryTransactions = "Unable to load transactions",
    errorUpdateRate = "Failed to update rate",
    importTitle = "Import Statement",
    chooseImportMethod = "Choose import method",
    selectPdf = "Select PDF",
    takePhoto = "Take Photo",
    analyzingStatement = "Analyzing statement...",
    importingTransactions = "Importing transactions...",
    importedCount = { count -> "Imported: $count" },
    importFound = { "Found: $it" },
    importDuplicates = { "Duplicates: $it" },
    importReadyCount = { ready, total -> "Ready to import: $ready of $total" },
    importNoCategory = { "No category: $it" },
    importButton = { "Import ($it)" },
    importNeedsReview = { "Need review ($it)" },
    importRecognized = { "Recognized ($it)" },
    importAccountLabel = "Import account",
    importSelectAccount = "Select account",
    start = "Start",
    next = "Next",
    skip = "Skip",
    onboardingSetupTitle = "How would you like to start?",
    onboardingSignInRestore = "Sign in and restore data",
    onboardingCreateNewAccount = "Create new account",
    onboardingSkipForNow = "Skip for now",
    onboardingSyncing = "Restoring your data...",
    onboardingPage1Title = "Welcome!",
    onboardingPage1Desc = "Money Manager helps you track your expenses and income",
    onboardingPage2Title = "Track your finances",
    onboardingPage2Desc = "Add transactions, organize by categories, and monitor your balance",
    onboardingPage3Title = "Analyze your spending",
    onboardingPage3Desc = "Charts and statistics help you understand where your money goes",
    createFirstAccount = "Create your first account",
    createFirstAccountSubtitle = "Enter a name, currency, and initial balance",
    accountMain = "Main",
    initialBalance = "Initial Balance",
    creating = "Creating...",
    createAccount = "Create Account",
    accountSectionTitle = "Account",
    signInSubtitle = "Sign in to sync your data",
    signInWithGoogle = "Sign in with Google",
    userAvatar = "User avatar",
    signOut = "Sign out",
    currencyPair = "Currency Pair",
    currentPair = "Current pair",
    baseCurrency = "Base",
    targetCurrency = "Target",
    searchCurrency = "Search currency",
    currentMonth = "This month",
    thirtyDays = "30 days",
    selectMonth = "Select month",
    selectRange = "Select range",
    customRange = "Range",
    recurringTransactions = "Recurring transactions",
    noRecurringTransactions = "No recurring transactions",
    daily = "Daily",
    weekly = "Weekly",
    monthly = "Monthly",
    yearly = "Yearly",
    startDate = "Start date",
    endDate = "End date",
    nextDate = "Next date",
    lastGeneratedDateLabel = "Last payment",
    frequency = "Frequency",
    dayOfMonth = "Day of month",
    dayOfWeek = "Day of week",
    dayOfWeekShort = listOf("Mo", "Tu", "We", "Th", "Fr", "Sa", "Su"),
    paused = "Paused",
    newRecurring = "New recurring",
    editRecurring = "Edit recurring",
    budgets = "Budgets",
    budget = "Budget",
    limit = "Limit",
    spent = "Spent",
    remaining = "Remaining",
    overBudget = "Over budget",
    newBudget = "New budget",
    noBudgets = "No budgets",
    monthlyLimit = "Monthly limit",
    exportCsv = "Export to CSV",
    exportComplete = "Export complete",
    exportError = "Export error",
    exporting = "Exporting...",
    settingsTitle = "Settings",
    sectionAccount = "Account",
    sectionGeneral = "General",
    sectionAppearance = "Appearance",
    sectionAbout = "About",
    categoriesManagement = "Categories",
    categoriesSubtitle = "Manage categories",
    rateLabel = { base, target -> "Rate $base/$target" },
    rateNotLoaded = "Rate not loaded yet",
    rateAsOf = { date -> "Rate as of $date" },
    loadRate = "Load NBK rate",
    updatingRate = "Updating...",
    loadRateSubtitle = "Fetch the latest NBK exchange rate",
    themeLabel = "Theme",
    themeSystem = "System",
    themeLight = "Light",
    themeDark = "Dark",
    languageLabel = "Language",
    versionLabel = "Version",
    developerLabel = "Developer",
    syncData = "Data sync",
    syncing = "Syncing...",
    synced = "Synced",
    syncError = "Sync error",
    syncRetryHint = "Tap to retry",
    updatedAt = { time -> "Updated $time" },
    rateError = "Failed to update exchange rate",
)

val KazakhStrings = AppStrings(
    locale = Locale("kk"),
    ok = "OK",
    cancel = "Болдырмау",
    save = "Сақтау",
    saving = "Сақталуда...",
    back = "Артқа",
    delete = "Жою",
    done = "Дайын",
    tryAgain = "Қайталап көру",
    search = "Іздеу",
    clearSearch = "Тазалау",
    all = "Барлығы",
    other = "Басқа",
    navTransactions = "Басты",
    navAccounts = "Шоттар",
    navStatistics = "Статистика",
    navSettings = "Параметрлер",
    expense = "Шығыс",
    income = "Кіріс",
    appName = "Money Manager",
    importStatement = "Үзінді импорттау",
    filterAll = "Барлығы",
    filterExpenses = "Шығыстар",
    filterIncome = "Кірістер",
    periodToday = "Бүгін",
    periodYesterday = "Кеше",
    periodWeek = "Апта",
    periodMonth = "Ай",
    periodYear = "Жыл",
    nothingFound = "Ештеңе табылмады",
    tryChangingQuery = "Сұрауды өзгертіп көріңіз",
    noTransactions = "Транзакциялар жоқ",
    addFirstTransaction = "Бірінші транзакцияны қосыңыз",
    originalAmount = "Бастапқы",
    periodDay = "Күн",
    searchTransactions = "Транзакцияларды іздеу...",
    savedPercent = { percent -> "Кірістің $percent% сақталды" },
    incomeCardLabel = "КІРІС",
    expenseCardLabel = "ШЫҒЫС",
    balanceCardLabel = "БАЛАНС",
    editTransaction = "Өңдеу",
    newTransaction = "Жаңа транзакция",
    amount = "Сома",
    category = "Санат",
    date = "Күні",
    note = "Ескертпе",
    noteHint = "Транзакция сипаттамасы",
    chooseCategory = "Санатты таңдаңыз",
    categoriesTitle = "Санаттар",
    noCategories = "Санаттар жоқ",
    editCategory = "Өңдеу",
    newCategory = "Жаңа санат",
    name = "Атауы",
    categoryNameHint = "Санат атауы",
    icon = "Белгіше",
    color = "Түсі",
    accountsTitle = "Шоттар",
    totalBalance = "Жалпы баланс",
    allAccounts = "Барлық шоттар",
    noAccounts = "Шоттар жоқ",
    active = "Белсенді",
    selectAccount = "Таңдау",
    noAccountsWarning = "Алдымен шот жасаңыз",
    editAccount = "Өңдеу",
    newAccount = "Жаңа шот",
    accountNameHint = "Шот атауы",
    currency = "Валюта",
    statisticsTitle = "Статистика",
    expensesByDays = "КҮН БОЙЫНША ШЫҒЫСТАР",
    byCategory = "Санат бойынша",
    noDataForPeriod = "Таңдалған кезең үшін деректер жоқ",
    expensesUpper = "ШЫҒЫСТАР",
    incomeUpper = "КІРІСТЕР",
    expensesLabel = "Шығыстар",
    incomeLabel = "Кірістер",
    totalExpenses = "Жалпы шығыстар",
    totalIncome = "Жалпы кірістер",
    incomeByDays = "КҮН БОЙЫНША КІРІСТЕР",
    statisticsChartByDay = { subject -> "$subject күн бойынша" },
    statisticsChartByMonth = { subject -> "$subject ай бойынша" },
    statisticsDateRangeSingleMonth = { month, startDay, endDay, year -> "$month $startDay-$endDay, $year" },
    statisticsDateRangeCrossMonth = { start, end, year -> "$start - $end, $year" },
    statisticsDateRangeCrossYear = { start, end -> "$start - $end" },
    mixedCurrencyUnavailable = "Жиынтықты түрлендіруге бағамдар жеткіліксіз",
    retryButton = "Қайталау",
    errorEnterAccountName = "Шот атауын енгізіңіз",
    errorEnterCategoryName = "Санат атауын енгізіңіз",
    errorEnterValidAmount = "Дұрыс сома енгізіңіз",
    errorSelectCategory = "Санатты таңдаңыз",
    errorSelectAccount = "Шотты таңдаңыз",
    errorEndDateBeforeStart = "Аяқталу күні басталу күнінен кейін болуы керек",
    errorEnterValidLimit = "Дұрыс шек енгізіңіз",
    errorReadingPdf = "PDF оқу қатесі",
    errorUnknown = "Белгісіз қате",
    errorNoTransactionsFound = "Құжатта транзакциялар табылмады",
    errorSelectAccountForImport = "Импортқа шот таңдаңыз",
    errorImport = "Импорт қатесі",
    errorNoInternet = "Интернет байланысы жоқ",
    errorSignInFailed = "Кіру сәтсіз. Қайта көріңіз",
    errorLoadCategoryTransactions = "Транзакцияларды жүктеу мүмкін болмады",
    errorUpdateRate = "Бағамды жаңарту сәтсіз",
    importTitle = "Үзінді импорттау",
    chooseImportMethod = "Импорт әдісін таңдаңыз",
    selectPdf = "PDF таңдау",
    takePhoto = "Фото түсіру",
    analyzingStatement = "Үзінді талдануда...",
    importingTransactions = "Транзакциялар импортталуда...",
    importedCount = { count -> "Импортталды: $count" },
    importFound = { "Табылды: $it" },
    importDuplicates = { "Көшірмелер: $it" },
    importReadyCount = { ready, total -> "Импортқа: $ready / $total" },
    importNoCategory = { "Санатсыз: $it" },
    importButton = { "Импорт ($it)" },
    importNeedsReview = { "Тексеруді қажет етеді ($it)" },
    importRecognized = { "Танылған ($it)" },
    importAccountLabel = "Импорт шоты",
    importSelectAccount = "Шотты таңдаңыз",
    start = "Бастау",
    next = "Келесі",
    skip = "Өткізіп жіберу",
    onboardingSetupTitle = "Қалай бастағыңыз келеді?",
    onboardingSignInRestore = "Кіру және деректерді қалпына келтіру",
    onboardingCreateNewAccount = "Жаңа шот жасау",
    onboardingSkipForNow = "Әзірге өткізу",
    onboardingSyncing = "Деректер қалпына келтірілуде...",
    onboardingPage1Title = "Қош келдіңіз!",
    onboardingPage1Desc = "Money Manager шығыстарыңыз бен кірістеріңізді бақылауға көмектеседі",
    onboardingPage2Title = "Қаржыны бақылаңыз",
    onboardingPage2Desc = "Транзакциялар қосыңыз, санаттарға бөліңіз және балансты бақылаңыз",
    onboardingPage3Title = "Шығыстарды талдаңыз",
    onboardingPage3Desc = "Графиктер мен статистика ақшаның қайда жұмсалатынын түсінуге көмектеседі",
    createFirstAccount = "Бірінші шотты жасаңыз",
    createFirstAccountSubtitle = "Атауын, валютасын және бастапқы балансын енгізіңіз",
    accountMain = "Негізгі",
    initialBalance = "Бастапқы баланс",
    creating = "Жасалуда...",
    createAccount = "Шот жасау",
    accountSectionTitle = "Аккаунт",
    signInSubtitle = "Деректерді синхрондау үшін кіріңіз",
    signInWithGoogle = "Google арқылы кіру",
    userAvatar = "Пайдаланушы аватары",
    signOut = "Шығу",
    currencyPair = "Валюта жұбы",
    currentPair = "Ағымдағы жұп",
    baseCurrency = "Негізгі",
    targetCurrency = "Мақсатты",
    searchCurrency = "Валюта іздеу",
    currentMonth = "Ағымдағы ай",
    thirtyDays = "30 күн",
    selectMonth = "Айды таңдау",
    selectRange = "Кезеңді таңдау",
    customRange = "Кезең",
    recurringTransactions = "Тұрақты төлемдер",
    noRecurringTransactions = "Қайталанатын транзакциялар жоқ",
    daily = "Күн сайын",
    weekly = "Апта сайын",
    monthly = "Ай сайын",
    yearly = "Жыл сайын",
    startDate = "Басталу күні",
    endDate = "Аяқталу күні",
    nextDate = "Келесі күн",
    lastGeneratedDateLabel = "Соңғы төлем",
    frequency = "Жиілік",
    dayOfMonth = "Ай күні",
    dayOfWeek = "Апта күні",
    dayOfWeekShort = listOf("Дс", "Сс", "Ср", "Бс", "Жм", "Сб", "Жс"),
    paused = "Тоқтатылған",
    newRecurring = "Жаңа төлем",
    editRecurring = "Өңдеу",
    budgets = "Бюджеттер",
    budget = "Бюджет",
    limit = "Шек",
    spent = "Жұмсалды",
    remaining = "Қалдық",
    overBudget = "Бюджет асып кетті",
    newBudget = "Жаңа бюджет",
    noBudgets = "Бюджеттер жоқ",
    monthlyLimit = "Айлық шек",
    exportCsv = "CSV-ге экспорт",
    exportComplete = "Экспорт аяқталды",
    exportError = "Экспорт қатесі",
    exporting = "Экспортталуда...",
    settingsTitle = "Параметрлер",
    sectionAccount = "Аккаунт",
    sectionGeneral = "Жалпы",
    sectionAppearance = "Безендіру",
    sectionAbout = "Қолданба туралы",
    categoriesManagement = "Санаттар",
    categoriesSubtitle = "Санаттарды басқару",
    rateLabel = { base, target -> "$base/$target бағамы" },
    rateNotLoaded = "Бағам әлі жүктелмеген",
    rateAsOf = { date -> "$date күнгі бағам" },
    loadRate = "ҰБ бағамын жүктеу",
    updatingRate = "Жаңартылуда...",
    loadRateSubtitle = "Ұлттық банктің соңғы бағамын алу",
    themeLabel = "Тақырып",
    themeSystem = "Жүйелік",
    themeLight = "Ашық",
    themeDark = "Қараңғы",
    languageLabel = "Тіл",
    versionLabel = "Нұсқасы",
    developerLabel = "Әзірлеуші",
    syncData = "Деректерді синхрондау",
    syncing = "Синхрондалуда...",
    synced = "Синхронданды",
    syncError = "Синхрондау қатесі",
    syncRetryHint = "Қайталау үшін басыңыз",
    updatedAt = { time -> "Жаңартылды $time" },
    rateError = "Бағамды жаңарту сәтсіз аяқталды",
)

val LocalStrings = staticCompositionLocalOf<AppStrings> { RussianStrings }

fun appStringsFor(languageCode: String): AppStrings = when (languageCode) {
    "en" -> EnglishStrings
    "kk" -> KazakhStrings
    else -> RussianStrings
}
